class ReportsController < ApplicationController
  def show
    ticker = params[:ticker]
    return head :not_found unless ticker.present?
    @company = Company.find_by(ticker: ticker)
  end

  def create
    ticker = report_params[:ticker].downcase
    @company = Company.find_by(ticker: ticker)
    return head :not_found unless @company

    redirect_to reports_path(ticker: ticker)
  end

  def gpt
    res_gpt = {"total_revenue":{"query":"What was the total revenue?","result":"The total revenue for 2022, 2021, and 2020 were $223,546 million, $212,981 million, and $169,559 million, respectively."},"gross_margin":{"query":"What was the gross margin?","result":"The total gross margin was $170,782 million in 2022, $152,836 million in 2021, and $104,956 million in 2020. The gross margin percentage was 43.3% in 2022, 41.8% in 2021, and 38.2% in 2020."},"net_income":{"query":"What was the net income?","result":"The net income was $99,803 in 2022, $94,680 in 2021, and $57,411 in 2020."},"op_ex":{"query":"What were the operational expenses?","result":"The operational expenses were $51,345 million in 2022, $43,887 million in 2021, and $38,668 million in 2020. These expenses include Research and Development ($26,251 million in 2022) and Selling, General and Administrative ($25,094 million in 2022)."},"op_inc":{"query":"What was the operational income?","result":"For 2022, 2021, and 2020, the operating income is $119.44 million, $108.95 million, and $66.29 million, respectively."},"taxes":{"query":"How much money went to taxes?","result":"The total provision for income taxes was $19.3 billion in 2022, $14.5 billion in 2021, and $9.7 billion in 2020."},"fcf":{"query":"What can you tell me about the cashflow?","result":"The Company believes its balances of cash, cash equivalents and unrestricted marketable securities, totaling $156.4 billion as of September 24, 2022, along with cash generated by ongoing operations and continued access to debt markets, will be sufficient to satisfy its cash requirements and capital return. The Consolidated Statements of Cash Flows are available for review, but specific details about cash flow are not provided in this context."}}

    @gpt_responses = {}
    res_gpt.each do |k, v|
      @gpt_responses[k] = v[:result]
    end
    render turbo_stream: turbo_stream.replace('openai', partial: 'reports/gpt')
  end

  def llama
    source_url = 'https://www.sec.gov/Archives/edgar/data/0000320193/000032019322000108/aapl-20220924.htm'
    @response = ModelsClient.generate(source_url)
    render turbo_stream: turbo_stream.replace('llama', partial: 'reports/llama')
  end

  def report_params
    params.require(:report).permit(:ticker)
  end
end
