# fly.toml app configuration file generated for fastapi-phi on 2024-07-26T13:37:49+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fastapi-phi'
primary_region = 'ord'

[build]

[[mounts]]
  source = 'fastapillamadata'
  destination = '/root/.ollama'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'a100-40gb'
  memory = '32gb'
  cpu_kind = 'performance'
  cpus = 8
